inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
  TargetRubyVersion: 3.3

Bundler/OrderedGems:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
